enabled: true
replicaCount: 1
service:
  port: 80
image:
  registry: registry.todo.local:5000
  repository: todo-wbff-go
  tag: latest
container:
  port: 80
env:
  TZ: "Europe/Istanbul"
  APP_DEBUG: true
  TOKEN_SIGNING_KEY: "secret"
  TODO_SERVICE_BASE_URL: "http://todo-service-s.default.svc.cluster.local"
ingress:
  host: web.bff.todo.local
livenessProbe:
  httpGet:
    path: /status
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /status
  initialDelaySeconds: 15
  periodSeconds: 10
