package configs

const EnvironmentVariableNameAppDebug = "APP_DEBUG"
const EnvironmentVariableNameHTTPPort = "HTTP_PORT"
const EnvironmentVariableNameTodoDbHost = "TODO_DB_HOST"
const EnvironmentVariableNameTodoDbPort = "TODO_DB_PORT"
const EnvironmentVariableNameTodoDbUser = "TODO_DB_USER"
const EnvironmentVariableNameTodoDbPass = "TODO_DB_PASS"
const EnvironmentVariableNameTodoDbName = "TODO_DB_NAME"
const EnvironmentVariableNameTodoDbMaximumNumberOfOpenConnections = "TODO_DB_MAX_OPEN_CONNECTIONS"
const EnvironmentVariableNameTodoDbMaximumLifetimeOfConnectionInSeconds = "TODO_DB_MAX_LIFETIME_OF_CONNECTION"
const EnvironmentVariableNameTodoDbMaximumNumberOfIdleConnections = "TODO_DB_MAX_IDLE_CONNECTIONS"
const EnvironmentVariableNameTodoDbMaximumIdleTimeOfConnectionInSeconds = "TODO_DB_MAX_IDLE_TIME_OF_CONNECTION"
