enabled: true
replicaCount: 1
service:
  port: 80
image:
  registry: registry.todo.local:5000
  repository: todo-wui
  tag: latest
container:
  port: 80
env:
  TZ: "Europe/Istanbul"
ingress:
  host: www.todo.local
livenessProbe:
  httpGet:
    path: /status
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /status
  initialDelaySeconds: 15
  periodSeconds: 10
