GET {{base_url}}/api/users/{{user_id}}/todos
Accept: application/json

###
POST {{base_url}}/api/todos
Accept: application/json
Content-Type: application/json

{
  "user_id": "{{user_id}}",
  "label": "test item 1",
  "tags": [
    {
      "key": "COMPLETED"
    }
  ]
}

###
PUT {{base_url}}/api/todos/{{resource_id}}
Accept: application/json
Content-Type: application/json

{
  "user_id": "{{user_id}}",
  "label": "test item 2"
}

###
DELETE {{base_url}}/api/todos/{{resource_id}}
Accept: application/json

###
GET {{base_url}}/
Accept: text/plain

###
GET {{base_url}}/status
Accept: text/plain

###