POST {{base_url}}/auth/token-claims
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username = admin &
password = admin

> {% client.global.set("auth_token", response.body.token); %}

###
GET {{base_url}}/api/todos
Accept: application/json
Authorization: Bearer {{auth_token}}

###
POST {{base_url}}/api/todos
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/x-www-form-urlencoded

value = test item

###
PATCH {{base_url}}/api/todos/{{resource_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/x-www-form-urlencoded

completed = false

###
DELETE {{base_url}}/api/todos/{{resource_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}

###
GET {{base_url}}/
Accept: text/plain

###
GET {{base_url}}/status
Accept: text/plain

###